### ISSUE TITLE
Issues with building with source on ubuntu with gcc 4.8

### ISSUE THREAD

**Issue by meenal29** [akumuli/Akumuli#132]
std::atomic<unsigned int>’ is not derived from ‘std::atomic<_Tp*>’
make[2]: *** [libakumuli/CMakeFiles/akumuli.dir/stringpool.cpp.o] Error 1
make[1]: *** [libakumuli/CMakeFiles/akumuli.dir/all] Error 2
make: *** [all] Error 2

This comes while doing make -j ..

Tried gcc 4.9 but no luck...

**Comment by Lazin** [comment]
Hi,
I'm currently using gcc 4.8 in development environment and CI. What commands have you been using to build from source? I need more detail to be able to help.

**Comment by meenal29** [comment]
I also use gcc 4.8.1-2 specifically and ubuntu 12.4.
The commands I have used to build from source are,
cmake . ----> All libraries are found
make -j --->  my machine hangs... I need to restart it. error is in some crc32.cpp saying asm operand has impossible constraints. 

if you have any solution please reply

**Comment by meenal29** [comment]
automatic build does not work for ubuntu. Whenever I run prerequisites.sh  I get error message like 
ERROR: Unknown package manager: ubuntu
ubuntu

**Comment by Lazin** [comment]
Akumuli can't be built on 12.04 because of old gcc. I've tried some time ago and it didn't work out. It's also can't be built on a 32-bit machine. The later will be fixed in the future because I've already eliminated the root of the problem (reliance on mmap). It's not clear why 4.9 didn't work (maybe old std lib is the reason?). If build hangs you can try to call `make` without -j option or using some small number, e.g. -j2. It will limit the number of processes and memory use.

**Comment by meenal29** [comment]
I tried with make -j4 it does not hang but it gives same error.. So as u said we strictly need 64 bit machine and ubuntu > 12.4 to get it build

**Comment by meenal29** [comment]
Hi,

Finally make worked on ubuntu 14.4 with gcc 4.8 :)

Thanku.
