### ISSUE TITLE
prerequisite.sh fails on ubuntu

### ISSUE THREAD

**Issue by mmitkevich** [akumuli/Akumuli#154]
tried replace "debian" with "ubuntu" in switch but it didn't help.

Looks promising project. Did you do any benchmarks against LMDB and/or traildb ?
I understand these are more restricted engines (traildb is not DB, it's file format).

**Comment by Lazin** [comment]
It doesn't makes much sense to compare against LMDB because LMDB is a key-value store and Akumuli is a time-series database. LMDB is an embedded database and Akumuli is stand alone solution. You can use libakumuli as an embedded database but anyway, the interfaces of both DBs is too different to compare. TrailDB works with complex events but Akumuli is a numeric time-series database. This means that Akumuli can only work with simple data types (floats, integers and booleans) but it can aggregate and resample this data. With TrailDB you can only scan data and create materialized views.
