### ISSUE TITLE
Query failure

### ISSUE THREAD

**Issue by Lazin** [akumuli/Akumuli#208]
The query:

```
"group-aggregate": {
        "metric": "proc.stat.cpu",
        "step": "2m",
        "func": [
            "mean"
        ]
    },
    "range": {
        "from": "20170823T095610.565",
        "to": "20170825T095610.565"
    },
    "where": {
        "type": "system"
    },
    "order-by": "series"
}
```

resulted in [assert(newdelta <= step_)](https://github.com/akumuli/Akumuli/blob/65a7c611bb394a89c787cafa08fcbd6f8248479e/libakumuli/storage_engine/operators/aggregate.cpp#L165) assertion being triggered.

**Comment by akashgoswami** [comment]
I also faced the same assertion, my query is as following

{ 'group-aggregate': { metric: 'temperature', step: '500ms', func: [ 'mean' ] },
  range: 
   { from: '20171007T141149.737000000',
     to: '20171007T143247.529000000' },
  output: { format: 'csv', timestamp: 'raw' } 
}

last few log line
2017-10-07 23:25:38,081 Main [TRACE] Can't open next iterator because not found
2017-10-07 23:25:38,081 Main [TRACE] Can't open next iterator because not found
2017-10-07 23:25:38,081 Main [TRACE] Can't open next iterator because not found
