### ISSUE TITLE
Query returning OK , but no values

### ISSUE THREAD

**Issue by ssathasivan** [akumuli/Akumuli#213]
We are testing the Query part of akumuli using POST MAN . The following is the 
URL :- http://IPNAME:8181/api/query
Method :- POST
body :- raw

{
    "select": "a0",
    "range": {
        "from": "1505491200000000",
        "to":   "150549390000000"
    }
}

This should correspond to 9/15/2017 09:00:00 AM to  9/15/2017 09:45:00 AM in epoch nano seconds PST
I have shared the db files ate 
https://drive.google.com/open?id=0B8ovlYcW7j7VZHpraUNDU0xDTWM

We are sure that  there are records. but we get  200 K with no results. Any idea what is going wrong

**Comment by Lazin** [comment]
Can you try a wider time range? You can also use aggregate query with count function to check how many data points the time interval contains. BTW, I'm out for a weekend. I'll be able to download the files and take a closer look onto this on Monday.

**Comment by Lazin** [comment]
I downloaded the database files and opened them with ./akumulid on my machine. The data is there and it's it can be queried. The problem is that you're using wrong timestamp. It looks like microsecond timestamp (unix timestamp * 1 000 000) but it should be a nanosecond timestamp (unix timestamp * 1 000 000 000). I've added 000 to each timestamp and it returned the data.

curl --url localhost:8181/api/query -d '{ "select": "a0", "range": { "from": "1505491200000000000", "to": "150549390000000000" }}'

**Comment by ssathasivan** [comment]
CURL seems to be working fine but when we try to run from POSTMAN , nothing is returned any idea.

**Comment by Lazin** [comment]
I wasn't able to run this query with Postman because the query returns more than 1GB of text. Postman is to slow to process it and it looks like it holds all results in memory. So I added the `limit` clause to the query to return only 10 result and it worked.

This is the code that I generated using Postman (this app can generate the code, what a pleasant surprise!):

```golang
package main

import (
	"fmt"
	"strings"
	"net/http"
	"io/ioutil"
)

func main() {

	url := "http://localhost:8181/api/query"

	payload := strings.NewReader("{ \"select\": \"a0\", \"range\": { \"from\": \"1505491200000000000\", \"to\": \"150549390000000000\" }, \"limit\": 10 }")

	req, _ := http.NewRequest("POST", url, payload)

	req.Header.Add("cache-control", "no-cache")
	req.Header.Add("postman-token", "6153372b-a356-c42b-41fc-b14214f26c55")

	res, _ := http.DefaultClient.Do(req)

	defer res.Body.Close()
	body, _ := ioutil.ReadAll(res.Body)

	fmt.Println(res)
	fmt.Println(string(body))

}
```

This code also works as expected.

**Comment by ssathasivan** [comment]
This works... thanks
