### ISSUE TITLE
Support for Grafana

### ISSUE THREAD

**Issue by ssathasivan** [akumuli/Akumuli#214]
Hi ,

We have been using Akumuli for a use case of ours  and found out that it was a btter fit than influx... However we need some visualization component , for which we were thinking about Grafana.

Any idea how we can integrate grafana with Akumuli

If there is no grafana integration , if there any other tool we can use

Regards
Sabarish

**Comment by Lazin** [comment]
Grafana support is in progress (https://github.com/akumuli/akumuli.grafana). To finish this plugin I need to add some new API to akumulid.

**Comment by ssathasivan** [comment]
Is there any chance for this to be ready by October... We are trying to use Grafana as visualization tool or si there any other visualization libraries that you think we can use

**Comment by Lazin** [comment]
It shouldn't take long. I think it could be ready somewhere in October. You can use this plugin now, if you modify it a little bit. It can query the data already. The missing part is a auto-completion API. But you don't need this functionality since you're not using tags and there is a small amount of metric names that can be hardcoded in js.

**Comment by ssathasivan** [comment]
Will check this out

**Comment by akashgoswami** [comment]
In the meantime you could check node-akumuli package which works as a JSON simple data source plugin
