### ISSUE TITLE
Query questions

### ISSUE THREAD

**Issue by jinxmcg** [akumuli/Akumuli#255]
Hi,

Can I order results after aggregation count/sum?
What can I do about high cardinality eg counting access per domain and per user?

Thank you

**Comment by Lazin** [comment]
You can order results by series or by time using the "order-by" field. It doesn't work with "aggregate" query because "aggregate" returns only one element per series. With "group-aggregate" you can do

```
    {
	"group-aggregate":{
	    "metric":"access",
	    "step":"1m",
	    "func":["count"]
	},
        "order-by": "series",
	"where" : {
	    "domain":"www.yahoo.com",
	    "user": "13"
	},
	"range":{
	    "from":"1520612217943862700",
	    "to":"` + tmp + `"
	},
	"output": { "format": "csv" }
    }
```
or alternatively, you can add `"order-by": "time"`.

Cardinality is an issue now. The storage uses some amount of memory per series (8KB for small series, 12KB for large series, and up to 24KB for extreamly large ones). So now you need to multiply the cardinality of the dataset by one of these numbers. This will change in the future (once I finish the feature that I'm developing in the `input_logging` branch).
