### ISSUE TITLE
Loading Akumuli

### ISSUE THREAD

**Issue by togo59** [akumuli/Akumuli#280]
Akumuli is loaded on a remote server running Centos 7.2. The latest version of Grafana is also running on the same server and I am accessing it from my local PC.

I am using the Julia programming language from my local PC to load Akumuli by writing to a TCPSocket. I know I am talking to Akumuli because if I send (say) a badly formed timestamp, I get the correct -PARSE ERROR. When I don't get an error I assume the data has been transferred but I can't see it using Grafana. This could be a Grafana bug or perhaps I have not set it up correctly using the Akumuli-Grafana plugin.

1. Do you think this is a Grafana issue or could there be something blocking a successful write?
2. Is there a better/faster and more robust way of transferring data from my program? E.g. ZMQ?

**Comment by togo59** [comment]
Oh and BTW -- I am using port 8282 (TCP) but I have tried using a UDPSocket() and 8383. I have obviously opened the ports on the server firewall using the correct protocols. There is no problem with server access.

**Comment by Lazin** [comment]
There is an easier way to send data using OpenTSDB protocol. It's more verbose and less efficient but there are client libraries for different languages.
To check if the data is written correctly you can use the aggregate query with count function. Also, it's a good idea to check the log. Akumuli drops the connection and writes error message to the log (and tries to send it to client if client is receiving) if there is any problem with the incoming data.
The state of things with visibility/diagnostics is a major concern right now and it will be improved in the future. I'll be glad to help with problem diagnostics right away, feel free to ask.

**Comment by togo59** [comment]
Thank you. Actually, it has suddenly decided to work! But not reliably. I want to use Akumuli as part of a real-time control system I am building for a (very large) robotics project and so I need a very fast way of pushing the data into it. I am going to start by loading some earlier recorded data, each file I intend to read from is several GBytes. I will persevere and keep you informed. I'll also keep an eye on the log. BTW I have been using Druid up to now but Druid insists the data is wrapped in JSON, which is such a waste. I prefer your way of data representation!

**Comment by Lazin** [comment]
I guess that the reason is that you're using UDP endpoint. Akumuli can accept data only with increasing timestamps (which is OK for monitoring workloads) and if you'll try to write something out of order it will report an error. In case of UTC endpoint it will write message to log and drop the packet.

So, this is what could happen. You send packets with payload to UDP endpoint. Each packet has data points from many different series with close timestamps. Packets gets reordered and Akumuli drops some fraction of them (the once that came late).

The UDP endpoints designed with other use case in mind. If you have many clients and each one of those clients sends only its own series. For instance, some devices that send UDP packets with payload once every 10s. In this case individual UDP packets can be reorderd but it doesn't matter because Akumuli requires only timestamp from individual time-series to be in-order.

For your case I can recommend to use TCP. TCP endpoint is more performant since it can process many connections in parallel. It can also process data pretty fast. In my testing I use large gzip archives (many GB compressed) that contains compressed RESP data. I send them using this bash snippet:

```
cat arch.gz | unzip > /dev/tcp/127.0.0.1/8282
```

It can process around 2GB of text data (RESP encoded) per minute per core in this case.

**Comment by togo59** [comment]
No problems now. Thank you.
