### ISSUE TITLE
Invalid join query result

### ISSUE THREAD

**Issue by webfolderio** [akumuli/Akumuli#359]
Hi,

I am trying to use join query and Akumuli returns invalid result. I tried use both **csv** and **resp** output but result format is not correct and some values are missing. My query and sample data seems correct but i don't understand what is wrong?

Akumuli version: 0.8.80 (installed via packagecloud.io)
OS: Ubuntu 18.04

Here is my simple test case to produce invalid join query result:

**test data**
```bash
printf "+hdd.usage location=xyz\n:1574238775392000000\n:10\n" | netcat localhost 8282
printf "+hdd.usage location=xyz\n:1574238775393000000\n:11\n" | netcat localhost 8282
printf "+cpu.usage location=xyz\n:1574238775394000000\n:12\n" | netcat localhost 8282
printf "+cpu.usage location=xyz\n:1574238775395000000\n:13\n" | netcat localhost 8282
printf "+mem.usage location=xyz\n:1574238775396000000\n:14\n" | netcat localhost 8282
printf "+mem.usage location=xyz\n:1574238775397000000\n:15\n" | netcat localhost 8282
```

**select hdd.usage**
```bash
curl --header "Content-Type: application/json" --request POST --data '{"output": {"format": "csv", "timestamp": "raw"}, "select": "hdd.usage", "range":{"from":"1574238775391000000","to":"1574238775398000000"}}' http://localhost:8181/api/query
```

:white_check_mark: **valid response**

```
hdd.usage location=xyz,ts=1574238775392000000,10
hdd.usage location=xyz,ts=1574238775393000000,11
```

**select cpu.usage**
```bash
curl --header "Content-Type: application/json" --request POST --data '{"output": {"format": "csv", "timestamp": "raw"}, "select": "cpu.usage", "range":{"from":"1574238775391000000","to":"1574238775398000000"}}' http://localhost:8181/api/query
```

:white_check_mark: **valid response**

```
cpu.usage location=xyz,ts=1574238775394000000,12
cpu.usage location=xyz,ts=1574238775395000000,13
```

**select mem.usage**

```bash
curl --header "Content-Type: application/json" --request POST --data '{"output": {"format": "csv", "timestamp": "raw"}, "select": "mem.usage", "range":{"from":"1574238775391000000","to":"1574238775398000000"}}' http://localhost:8181/api/query
```

:white_check_mark: **valid response**

```
mem.usage location=xyz,ts=1574238775396000000,14
mem.usage location=xyz,ts=1574238775397000000,15
```

**join hdd.usage, cpu.usage, mem.usage**

```bash
curl --header "Content-Type: application/json" --request POST --data '{"output": {"format": "csv", "timestamp": "raw"}, "join": ["hdd.usage", "cpu.usage", "hdd.usage"], "range":{"from":"1574238775391000000","to":"1574238775398000000"}}' http://localhost:8181/api/query
```

:red_circle: **Invalid response**

```
hdd.usage|cpu.usage|hdd.usage location=xyz,ts=1574238775392000000,10,,10
hdd.usage|cpu.usage|hdd.usage location=xyz,ts=1574238775393000000,11,,11
hdd.usage|cpu.usage|hdd.usage location=xyz,ts=1574238775394000000,,12,
```

**Comment by Lazin** [comment]
The output looks OK. The join query in Akumuli is supposed to work as full outer join in SQL. It joins values by timestamp and if some timestamps are missing in some series the result will have gaps.

So, the output you see is expected because in the input cpu.usage and hdd.usage don't overlap by time. If you'll join them you'll always have gaps in the output.

This feature is supposed to be used in situations when the data is generated in bulk format and you want to retrieve it in the same manner. The usage example can be found in this test - https://github.com/akumuli/Akumuli/blob/master/functests/roundtrip.sh. This test downloads and writes data in bulk format and then it uses the join query to create the result that matches the input and can be compared to the input using `diff` tool.

**Comment by webfolderio** [comment]
Thanks for the clarification.
